### ISSUE TITLE
Need new SQL dump on request.

### ISSUE THREAD

**Issue by Ankan0011** [a3mc/Casper-Metrics#3]
I am Master's student writing my thesis on transaction analytics of Casper. I am looking for an indexer project which I can use to collect Casper transaction data for an analytics project. Can admin please provide an updated dump which can be used for academic analytics purpose only ?

Thank.

**Comment by matsuro-hadouken** [comment]
Hello @Ankan0011 here is database carefully exported for your needs at block `1207880`. If we can help on something also please let us know. https://bit.ly/3VW08Se Here is unpublished feature of the platform which can be interesting: https://caspermetrics.io/stake you can test by using any ART3MIS delegator public key as for example: `01a60e0885f4968dd3107e088b4cb5798af665859b769bc1aa86909a5b67f66a66` Good luck on research !

**Comment by Ankan0011** [comment]
Thanks for uploading the updated dump. I just want to confirm a few things regarding the dump tables. Is the Users tables contains the details of all the validators as well, I also looking for the address/id's of the validators as well ?

**Comment by uchu** [comment]
@Ankan0011 It is a table for the administation panel. You can keep it empty.

**Comment by uchu** [comment]
There is no valuable info into it

**Comment by uchu** [comment]
@Ankan0011 currently you can't easily get the validators details from the database. It exist experimentally for one validator, but it might not be helpfull for your purposes. Let us know please if we can help with something else and thank you!

**Comment by Ankan0011** [comment]
Thanks a lot for your help. I will keep looking for validators info from public API's.

**Comment by Sinaniya** [comment]
Hi, can I ask for an up-to-date snapshot of Casper mainnet data?

**Comment by matsuro-hadouken** [comment]
> Hi, can I ask for an up-to-date snapshot of Casper mainnet data?

 Hope it helps: `161.97.84.146/mysqldump_22_May_2023_13_35_19.sql`

**Comment by Sinaniya** [comment]
Thanks @matsuro-hadouken.
